### ISSUE TITLE
testing issue with config.json

### ISSUE THREAD

**Issue by dydFreeman** [fulls1z3/ngx-config#138]
**I'm submitting a ...**  (check one with "x")
```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <!-- Please check the repository for a similar issue or PR before submitting -->
[X] Support request => <!-- Please check the repository for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
```

**Current behavior**

I started testing components on my app but i got stucked with the @ngx-config loading. 

**app.module.ts**

```
    export function configFactory(http: Http): ConfigLoader {
      return new ConfigHttpLoader(http, './assets/config.json'); // API ENDPOINT
    }

    [...]
```

**app.component.ts**

```
    constructor(private translateService: TranslateService, authService: AuthService,
        router: Router, rideService: RideService, appConfigService: AppConfigService, infoService: InfoService) {
    
        this.feVersion = appConfigService.FEVersion;
        this.beVersion = infoService.getBEVersion();

    [...]
```

**appConfig.service.ts**    

```
    @Injectable()
    export class AppConfigService {
    
      constructor(private configService: ConfigService) { }
    
    get FEVersion(): string {
        return _.defaultTo(this.configService.getSettings('svnRevision'), '');
      }
```

**app.component.spec.ts**

```
    describe('AppComponent', () => {
    
      beforeEach(async(() => {
        TestBed.configureTestingModule({
          declarations: [
            AppComponent,
            [...lot of other components...]
          ],
          imports: [
            [...lot of modules...],
            ConfigModule.forRoot({
              provide: ConfigLoader,
              useFactory: (configFactory),
              deps: [Http]
            })
          ],
          providers: [
            { provide: APP_BASE_HREF, useValue: '/' },
            AppConfigService,
            {
              provide: LAZY_MAPS_API_CONFIG,
              useClass: MapsConfig,
              deps: [HttpClient]
            },
            AuthService,
            AuthGuard,
            ResearchService,
            RideService,
            GeoService,
            MailService,
            ConfirmationService,
            MessageService,
            VehicleService,
            InfoService,
            AuthRequestInterceptorProvider()
          ]
        }).compileComponents();
      }));
    
      it('should create the app', async(() => {
        const fixture = TestBed.createComponent(AppComponent);
        const app = fixture.debugElement.componentInstance;
        expect(app).toBeTruthy();
      }));
    });
```

**config.json**

```
    {
        "svnRevision": "412",
        [...]
    }
```

**ERROR:**

```
    Failed: No setting found with the specified key [svnRevision]!
    Error: No setting found with the specified key [svnRevision]!
        at ConfigService.webpackJsonp../node_modules/@ngx-config/core/@ngx-config/core.es5.js.ConfigService.getSettings node_modules/@ngx-config/core/@ngx-config/core.es5.js:38:1)
        at AppConfigService.get [as FEVersion] src/app/services/appConfig.service.ts:20:43)
        at new AppComponent src/app/app.component.ts:40:39)
        at createClass node_modules/@angular/core/esm5/core.js:12449:1)
        at createDirectiveInstance node_modules/@angular/core/esm5/core.js:12284:22)
        at createViewNodes node_modules/@angular/core/esm5/core.js:13742:38)
        at createRootView node_modules/@angular/core/esm5/core.js:13631:1)
        at callWithDebugContext node_modules/@angular/core/esm5/core.js:15056:26)
        at Object.debugCreateRootView [as createRootView] node_modules/@angular/core/esm5/core.js:14339:1)
        at ComponentFactory_.webpackJsonp../node_modules/@angular/core/esm5/core.js.ComponentFactory_.create node_modules/@angular/core/esm5/core.js:11236:26)
```

I can see on the devTools network tab that the config.json has has been loaded, so it's not a matter of karma not finding it or whatever.
It seems like the configService doesn't know where is the config.json.

**Expected/desired behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Environment**
* **Angular version:** 5.2.X

* **Browser:**
- [X] Chrome (desktop) version 66.0.3359
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

* **For Tooling issues:**
- Node version: 8.9.1  
- Platform:  Windows 

* Others:

**Comment by dydFreeman** [comment]
stackOverflow ref: https://stackoverflow.com/questions/50395266/unit-test-ngx-config-json-async-loading

**Comment by nhannqgh** [comment]
Stackoverflow link has died!

**Comment by f4irline** [comment]
Was anyone able to resolve this? The Stackoverflow link has died
